<TABLE width="450" border="0" cellspacing="0" cellpadding="0">
  <TR>
    <TD><B class=subhead>William M. Apfelbaum</B><BR>
        <B> Chairman of the Board</B> <IMG src="/_images/company/b_apfelbaum.jpg" width="117" height="175" align="right" hspace="10"><BR>
        William M. Apfelbaum, has served the company since early in 1998 and is currently the company's Worldwide Chairman. Mr. Apfelbaum was owner and CEO of TDI, the country's largest diversified outdoor media company for eleven years. Additionally, he held significant senior executive positions with Infinity Broadcasting, Westinghouse/CBS, and Gannett Transit, formerly New York Subways Advertising Co., Inc.
      <P>Mr. Apfelbaum currently serves on the board of several corporations. He is also involved in many philanthropic endeavors and in 1996, he founded the Apfelbaum Family Foundation through which he donates time and funds to various charitable organizations. Mr. Apfelbaum's public speaking engagements include guest lecturer at the Harvard Business School where his restructuring model is used as a case study. He also speaks at New York University and the London Business School. He has been profiled in publications such as Forbes, Chief Executive, Advertising Age, Marketing Week, Campaign and Crain's. He is a graduate of New York University.<BR>
      <BR>
      </P>
      <P><B class=subhead>Mitchell Cannold</B><BR>
         <B>President and Chief Executive Officer</B><IMG src="/_images/company/m_cannold.jpg" width="117" height="175" align="right" hspace="10"><BR>
       Mitchell Cannold brings to MaxWorldwide over 20 years of senior management experience at Sony Corporation, NBC News, CBS News and The Walt Disney Company.  During his seven years at Sony Corporation, he was President of Sony New Technologies, the corporation's New Business Development unit and concurrently led Sony Gateway, the company's strategic marketing partnership group.  Mr. Cannold also developed Sony Retail Entertainment, the company's location-based entertainment business unit and managed Sony Pictures' Imax business.</P>
      <P>Mr. Cannold launched and built Sony's corporate Internet businesses, Sony Online Ventures and Sony Online Entertainment, including Sony's highly successful online gaming site and was founding Chair of Sony's Internet Steering Committee.  As an Executive Producer, Mr. Cannold has produced over two-dozen motion pictures, five IMAX films and several Emmy winning network news documentaries and specials. <BR>
        Mr. Cannold is a graduate of UCLA.</P>
      <P><BR>
      </P>
      <P><B class=subhead>Dr. Peter Sealey</B><BR>
        <B>Chief Strategy Officer</B><IMG src="/_images/company/p_sealey.jpg" width="117" height="175" align="right"><BR>
        Dr. Peter Sealey has served as a Director of MaxWorldwide since August 1999 and is the founder and CEO of Los Altos Group, Inc., a Silicon Valley consulting firm specializing in business and marketing strategies.  He is also an Adjunct Professor of Marketing and Co-Director of the Center for Marketing and Technology at the Haas School of Business at the University of California, Berkeley. </P>
      <P>Dr. Sealey spent over 20 years with the Coca-Cola Company, where he held a variety of senior management positions including Senior Vice President, Global Marketing. He served as President of Marketing and Distribution at Columbia Pictures in the late 1980s where his releases included Ghostbusters, La Bamba, Karate Kid, Stand by Me and Tootsie. He is also a member of the Board of Directors and  an adviser to a number of technology companies. He holds a B.S. from the University of Florida, an M.I.A. from Yale University and a Ph.D. from the Claremont Graduate University's Peter F. Drucker Graduate Management Center.</P>
      <P><BR>
      </P>
      <P><STRONG class=subhead>Geoffry R. Handler</STRONG><BR>
        Geoffry R. Handler is the Managing Partner of McLaughlin &amp; Stern LLP and has participated on behalf of clients as corporate counsel in the purchase of a major league baseball franchise in New York.  Mr. Handler was a member of the Board of Directors at TDI, a major outdoor billboard company, until its acquisition by Infinity Broadcasting and sits on the Board of Directors of two major charitable foundations.</P>
      <P>A member of the Association of the Bar of the City of New York, Mr. Handler has been  involved in the restructuring of various medium and large sized family owned ventures to accomplish the often extremely complex intergenerational transfers. Mr. Handler received his B.S. degree from Massachusetts Institute of Technology and his J.D. degree from University of Chicago. <BR>
      </P>
      <P><BR>
      </P>
      <P><STRONG class=subhead>Bruce Redditt</STRONG><BR>
        Bruce Redditt has served as a director of MaxWorldwide, formerly L90, since September 1999. Since May 1998, Mr. Redditt has served as Executive Vice President of Omnicom Group Inc. His duties include overseeing Communicade, a division of Omnicom Group, which holds investment positions in companies specializing in Web-based, interactive media services. Between July 1995 and April 1998, Mr. Redditt was Executive Vice President of Sony Pictures Entertainment. Between July 1986 and June 1995, Mr. Redditt held a number of communication positions within GTE Corporation.  He graduated with a BS from Florida State University.<BR>
      </P>
      </TD>
  </TR>
</TABLE>