<TABLE width="700" border="0" cellspacing="0" cellpadding="5">
  <TR>
    <TD align="center"><FONT color="#333333" size="1" face="Verdana, Arial, Helvetica, sans-serif">Copyright 
      &copy;2002 MaxWorldwide, Inc. All Rights Reserved.</FONT><FONT size="1" face="Verdana, Arial, Helvetica, sans-serif"> 
      <A href="../privacy_policy/index.php" class="footer">Privacy Policy </A></FONT></TD>
  </TR>
</TABLE>
<P><BR></P>

